server:
  port: 9027

dubbo:
  application:
    name: ldm_server
  registry:
    address: zookeeper://120.26.187.19:2181
  protocol:
    name: dubbo
    port: 9028
  scan: com.raindrop.service
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.2:3306/ldm?charset=utf8mb4&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
