server:
  port: 9026
dubbo:
  application:
    name: ldm_api
  registry:
    address: zookeeper://localhost:2181
  scan: com.raindrop.api.Controller

spring:
  security:
    user:
      name: admin
      password: 123456
